# Generated by Django 5.2.12 on 2026-03-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('aged_care', 'Aged Care'), ('allied_health', 'Allied Health'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('rehabilitation', 'Rehabilitation'), ('pharmacy', 'Pharmacy'), ('physiotherapy', 'Physiotherapy'), ('other', 'Other')], max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('quick_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active_placements', 'Active placements'), ('upcoming_placements', 'Upcoming placements'), ('previous_placements', 'Previous placements'), ('potential', 'Potential'), ('not_available', 'Not available')], default='potential', max_length=30)),
                ('accepts_students', models.BooleanField(default=False)),
                ('orientation_required', models.BooleanField(default=False)),
                ('uniform_policy', models.TextField(blank=True)),
                ('parking_info', models.TextField(blank=True)),
                ('orientation_time', models.TimeField(blank=True, null=True)),
                ('start_time_day1', models.TimeField(blank=True, null=True)),
                ('mou_complete', models.BooleanField(default=False)),
                ('contacted_recently', models.BooleanField(default=False)),
                ('spots', models.PositiveIntegerField(default=0)),
                ('next_start', models.DateField(blank=True, null=True)),
                ('geo_raw', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_accuracy', models.CharField(choices=[('unknown', 'Unknown'), ('approximate', 'Approximate'), ('exact', 'Exact')], default='unknown', max_length=20)),
                ('geo_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'requirement',
                'verbose_name_plural': 'requirements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('days', models.CharField(max_length=255)),
                ('time_range', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='facilities.facility')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_shifts', to='facilities.program')),
            ],
            options={
                'verbose_name': 'facility shift',
                'verbose_name_plural': 'facility shifts',
                'ordering': ['facility__name', 'days', 'time_range'],
            },
        ),
        migrations.CreateModel(
            name='FacilityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='facilities.facility')),
                ('programs', models.ManyToManyField(blank=True, related_name='facility_contacts', to='facilities.program')),
            ],
            options={
                'verbose_name': 'facility contact',
                'verbose_name_plural': 'facility contacts',
                'ordering': ['facility__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='facilities.program'),
        ),
        migrations.CreateModel(
            name='FacilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_requirements', to='facilities.facility')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_requirements', to='facilities.program')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_requirements', to='facilities.requirement')),
            ],
            options={
                'verbose_name': 'facility requirement',
                'verbose_name_plural': 'facility requirements',
                'ordering': ['facility__name', 'requirement__name'],
                'unique_together': {('facility', 'requirement', 'program')},
            },
        ),
    ]
